### ISSUE TITLE
Pesquisa / Benchmark

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/whatsapp-webcrawler#2]
https://towardsdatascience.com/build-your-own-whatsapp-chat-analyzer-9590acca9014

Projetos no Github:
- Group Bot: https://github.com/Yukaru-san/WhatsApp-GroupBot
- https://github.com/vasani-arpit/WBOT
- https://github.com/danielcardeenas/sulla
- https://github.com/joaoricardo000/whatsapp-bot-seed
- https://github.com/pedroslopez/whatsapp-web.js
- https://github.com/VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api
- https://github.com/dharmaraj5610/WhatsApp-Chat-Analyzer-Using-Python
-

**Comment by ItaloRod** [comment]
Finalizado a solicitação do benchmark - coloquei os principais gráficos que pode ser retirado de cada um deles.
[BenchMark_Whatsapp.pdf](https://github.com/EscolaDeSaudePublica/whatsapp-webcrawler/files/4194361/BenchMark_Whatsapp.pdf)
